import { MenuItem, GalleryItem, CustomerReview, RestaurantHours } from '../types';

export const RESTAURANT_INFO = {
  name: 'Nala Bheema Restaurant',
  legalName: 'Nala Bheema Kitchen & Royal Hospitality Pvt. Ltd.',
  tagline: 'The Authentic Royal Kitchen of Culinary Legends',
  subheading: 'Inspired by the ancient masters Nala & Bheema, crafting time-honored recipes with stone-ground spices and pure desi ghee since 1994.',
  phone: '+91 98765 43210',
  altPhone: '+91 40 2345 6789',
  whatsappNumber: '919876543210',
  whatsappDisplay: '+91 98765 43210',
  email: 'dine@nalabheema.com',
  address: 'Plot No. 42, Royal Heritage Avenue, Jubilee Enclave, Hitec City Road',
  city: 'Hyderabad, Telangana',
  pincode: '500081',
  landmark: 'Near Cyber Towers & Shilparamam Cultural Village',
  googleMapsUrl: 'https://maps.google.com/?q=Nala+Bheema+Restaurant+Hyderabad',
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3806.326265001557!2d78.37525357493608!3d17.444062083453896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb93dc8c5d69df%3A0x19688ebb557fa321!2sHitec%20City%2C%20Hyderabad%2C%20Telangana!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin',
  social: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
    youtube: 'https://youtube.com',
  },
  stats: [
    { label: 'Culinary Legacy', value: '30+ Years' },
    { label: 'Secret Royal Recipes', value: '50+' },
    { label: 'Patrons Served', value: '500K+' },
    { label: 'Google & Zomato Rating', value: '4.9 ★' },
  ],
};

export const RESTAURANT_HOURS: RestaurantHours[] = [
  { day: 'Monday', lunch: '11:30 AM – 03:30 PM', dinner: '07:00 PM – 11:00 PM' },
  { day: 'Tuesday', lunch: '11:30 AM – 03:30 PM', dinner: '07:00 PM – 11:00 PM' },
  { day: 'Wednesday', lunch: '11:30 AM – 03:30 PM', dinner: '07:00 PM – 11:00 PM' },
  { day: 'Thursday', lunch: '11:30 AM – 03:30 PM', dinner: '07:00 PM – 11:00 PM' },
  { day: 'Friday', lunch: '11:30 AM – 03:30 PM', dinner: '07:00 PM – 11:30 PM', isSpecial: true },
  { day: 'Saturday', lunch: '11:30 AM – 04:00 PM', dinner: '07:00 PM – 11:30 PM', isSpecial: true },
  { day: 'Sunday', lunch: '11:30 AM – 04:00 PM', dinner: '07:00 PM – 11:30 PM', isSpecial: true },
];

export const MENU_ITEMS: MenuItem[] = [
  // Specials & Biryani
  {
    id: 'nb-special-biryani',
    name: 'Nala Bheema Royal Dum Biryani',
    teluguName: 'నల భీమ రాయల్ దమ్ బిర్యానీ',
    description: 'Slow-cooked in sealed earthen clay pot with long-grain aged Basmati rice, marinated tender meat, saffron milk, and secret heritage spice potli. Served with Mirchi Ka Salan & Dahi Raita.',
    price: 460,
    category: 'specials',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 3,
    portionSize: 'Serves 1–2',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    tags: ['Clay Pot', 'Signature', 'Royal Feast'],
  },
  {
    id: 'bamboo-chicken-biryani',
    name: 'Araku Bamboo Chicken Biryani',
    teluguName: 'అరకు వెదురు చికెన్ బిర్యానీ',
    description: 'Forest-style aromatic biryani packed inside tender green bamboo hollow and charcoal-roasted slowly over wood embers for an earthy, smoky flavor.',
    price: 490,
    category: 'biryani',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 3,
    portionSize: 'Serves 1–2',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    tags: ['Wood Smoked', 'Chef Secret'],
  },
  {
    id: 'zafrani-paneer-biryani',
    name: 'Nawabi Zafrani Paneer Biryani',
    teluguName: 'నవాబీ జఫ్రానీ పనీర్ బిర్యానీ',
    description: 'Fragrant Kashmiri saffron basmati rice layered with charcoal-grilled cottage cheese cubes, fresh mint, caramelized shallots, and golden cashews.',
    price: 380,
    category: 'biryani',
    isVeg: true,
    isChefSpecial: false,
    isBestseller: true,
    spicyLevel: 2,
    portionSize: 'Serves 1–2',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    tags: ['Pure Veg', 'Saffron Infused'],
  },
  {
    id: 'gongura-mutton-biryani',
    name: 'Heritage Gongura Mamsam Biryani',
    teluguName: 'గోంగూర మాంసం బిర్యానీ',
    description: 'Traditional tangy sorrel (gongura) leaf paste slow-braised with succulent lamb cuts and aromatic spices, layered into fragrant biryani rice.',
    price: 520,
    category: 'biryani',
    isVeg: false,
    isChefSpecial: true,
    spicyLevel: 4,
    portionSize: 'Serves 1–2',
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=800&q=80',
    tags: ['Fiery Andhra', 'Signature'],
  },

  // Starters & Tandoor
  {
    id: 'royyala-vepudu',
    name: 'Kakinada Royyala Vepudu (Prawn Fry)',
    teluguName: 'కాకినాడ రొయ్యల వేపుడు',
    description: 'Fresh coastal prawns tossed with cracked black pepper, curry leaves, crushed garlic, and shallots in cold-pressed sesame oil.',
    price: 480,
    category: 'starters',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 4,
    portionSize: 'Platter of 8-10 prawns',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    tags: ['Seafood Special', 'Crispy & Spicy'],
  },
  {
    id: 'nala-bheema-chicken-roast',
    name: 'Nala Bheema Ghee Roast Chicken',
    teluguName: 'నల భీమ నేతి చికెన్ రోస్ట్',
    description: 'Tender chicken morsels slow-roasted in pure country ghee with Byadgi chillies, whole spices, and roasted coriander seeds.',
    price: 420,
    category: 'starters',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 3,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    tags: ['Pure Desi Ghee', 'Bestseller'],
  },
  {
    id: 'tandoori-malai-paneer-tikka',
    name: 'Shahi Malai Paneer Tikka',
    teluguName: 'షాహీ మలై పనీర్ టిక్కా',
    description: 'Silken cottage cheese blocks marinated in hung curd, green cardamom, roasted gram flour, and cream, blistered in clay oven.',
    price: 360,
    category: 'starters',
    isVeg: true,
    isChefSpecial: false,
    isBestseller: true,
    spicyLevel: 1,
    portionSize: '6 Large pieces',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80',
    tags: ['Mild & Creamy', 'Tandoor'],
  },
  {
    id: 'crispy-corn-pepper-fry',
    name: 'Nellore Pepper Corn Salt & Fry',
    teluguName: 'మిరియాల కార్న్ ఫ్రై',
    description: 'Golden sweet corn kernels tossed with freshly crushed black peppercorns, scallions, diced bell peppers, and fresh curry leaves.',
    price: 290,
    category: 'starters',
    isVeg: true,
    isChefSpecial: false,
    spicyLevel: 2,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    tags: ['Crunchy', 'Quick Bite'],
  },

  // Royal Curries & Gravies
  {
    id: 'natu-kodi-pulusu',
    name: 'Rayalaseema Natu Kodi Pulusu',
    teluguName: 'రాయలసీమ నాటుకోడి పులుసు',
    description: 'Authentic country chicken simmered in rich, peppery, poppy seed and coconut gravy with local country spices. Best paired with hot steamed rice or ragi mudda.',
    price: 470,
    category: 'curries',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 4,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    tags: ['Country Chicken', 'Authentic Legacy'],
  },
  {
    id: 'gongura-mutton-curry',
    name: 'Amravati Gongura Mutton Gravy',
    teluguName: 'అమరావతి గోంగూర మటన్ కూర',
    description: 'Slow-braised young goat meat simmered in tangy stone-ground gongura gravy with Guntur red chillies and fenugreek tadka.',
    price: 530,
    category: 'curries',
    isVeg: false,
    isChefSpecial: true,
    spicyLevel: 4,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    tags: ['Royal Andhra', 'Spicy'],
  },
  {
    id: 'gutti-vankaya-koora',
    name: 'Traditional Gutti Vankaya Koora',
    teluguName: 'గుత్తి వంకాయ కూర',
    description: 'Tender baby brinjals stuffed with roasted peanut, sesame, dry coconut, and coriander spice paste, simmered in a velvet tamarind gravy.',
    price: 340,
    category: 'curries',
    isVeg: true,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 2,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    tags: ['Traditional Favorite', 'Nutty Gravy'],
  },
  {
    id: 'paneer-butter-masala',
    name: 'Shahi Paneer Makhani Bheema',
    teluguName: 'షాహీ పనీర్ మఖానీ',
    description: 'Fresh farm cottage cheese simmered in slow-roasted plum tomato, cashew cream, and churned butter gravy with kasuri methi.',
    price: 350,
    category: 'curries',
    isVeg: true,
    isChefSpecial: false,
    isBestseller: true,
    spicyLevel: 1,
    portionSize: 'Serves 2',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    tags: ['Rich Butter Gravy', 'Family Favorite'],
  },

  // Royal Thalis & Combos
  {
    id: 'nala-bheema-raja-thali',
    name: 'Nala Bheema Raja Bhojanam Thali (Non-Veg)',
    teluguName: 'నల భీమ రాజ భోజనం థాలి',
    description: 'The emperor feast served on brass plate with fresh banana leaf: Mutton Biryani, Natu Kodi Pulusu, Royyala Vepudu, Dal Fry, Sambar, Rasam, Curd, 2 Butter Naans, Sweet Puran Poli & Paan.',
    price: 699,
    category: 'thalis',
    isVeg: false,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 3,
    portionSize: 'Grand Feast for 1',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80',
    tags: ['Grand Banquet', 'Complete Feast'],
  },
  {
    id: 'swarna-rani-veg-thali',
    name: 'Swarna Rani Pure Veg Bhojanam',
    teluguName: 'స్వర్ణ రాణి వెజ్ భోజనం',
    description: 'Lavish traditional vegetarian banquet: Zafrani Pulao, Gutti Vankaya, Paneer Makhani, Mudda Pappu with pure cow ghee, Avakaya pickle, Gongura pachadi, Rasam, Sambar, Roti, and Gulab Jamun.',
    price: 499,
    category: 'thalis',
    isVeg: true,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 2,
    portionSize: 'Grand Feast for 1',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    tags: ['100% Pure Veg', 'Authentic Andhra'],
  },

  // Breads & Rice
  {
    id: 'butter-garlic-naan',
    name: 'Tandoori Butter Garlic Naan',
    teluguName: 'బటర్ గార్లిక్ నాన్',
    description: 'Leavened clay-oven flatbread topped with charred minced garlic, fresh coriander leaves, and lavish brush of salted butter.',
    price: 90,
    category: 'breads',
    isVeg: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    tags: ['Clay Oven Fresh'],
  },
  {
    id: 'malabar-parotta',
    name: 'Crispy Flaky Malabar Parotta (2 Pcs)',
    teluguName: 'మలబార్ పరోటా',
    description: 'Multi-layered, flaky, golden-brown griddled flatbread hand-beaten to soft flaky ribbons. Pairs exceptionally with royal gravies.',
    price: 110,
    category: 'breads',
    isVeg: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    tags: ['Flaky & Soft'],
  },

  // Desserts & Beverages
  {
    id: 'apricot-delight',
    name: 'Royal Khubani Apricot Delight',
    teluguName: 'ఖుబానీ కా మీఠా విత్ ఐస్ క్రీమ్',
    description: 'Slow-simmered Turkish dried apricots infused with cardamom and saffron, layered with rich rabri and vanilla bean ice cream.',
    price: 240,
    category: 'desserts',
    isVeg: true,
    isChefSpecial: true,
    isBestseller: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    tags: ['Hyderabadi Classic', 'Chef Special'],
  },
  {
    id: 'double-ka-meetha',
    name: 'Nizami Double Ka Meetha',
    teluguName: 'డబుల్ కా మీఠా',
    description: 'Crispy ghee-fried bread rounds soaked in saffron cardamom milk syrup, smothered with reduced khoya rabri and slivered pistachios.',
    price: 220,
    category: 'desserts',
    isVeg: true,
    isBestseller: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    tags: ['Melt In Mouth'],
  },
  {
    id: 'filter-kaapi',
    name: 'Heritage Degree Filter Coffee',
    teluguName: 'డిగ్రీ ఫిల్టర్ కాఫీ',
    description: 'Freshly decocted chicory-blend Chikmagalur coffee beans frothed high with piping hot farm fresh buffalo milk.',
    price: 90,
    category: 'beverages',
    isVeg: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    tags: ['Authentic Brass Dabarah'],
  },
  {
    id: 'spiced-buttermilk',
    name: 'Guntur Masala Majjiga (Spiced Buttermilk)',
    teluguName: 'మసాలా మజ్జిగ',
    description: 'Cooling churned curd beverage tempered with crushed ginger, green chillies, curry leaves, and roasted cumin powder.',
    price: 80,
    category: 'beverages',
    isVeg: true,
    spicyLevel: 1,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
    tags: ['Cooling & Refreshing'],
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Royal Dum Handi Biryani',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80',
    description: 'Handcrafted clay pots sealed with whole wheat dough for traditional dum slow-cooking.',
  },
  {
    id: 'gal-2',
    title: 'The Royal Majlis Dining Hall',
    category: 'ambience',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    description: 'Warm ambient lighting, authentic heritage wood carvings, and intimate private family dining cabanas.',
  },
  {
    id: 'gal-3',
    title: 'Sizzling Tandoor & Charcoal Kebabs',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    description: 'Live clay tandoors firing fresh kebabs and flaky buttery naans over glowing charcoal.',
  },
  {
    id: 'gal-4',
    title: 'Grand Raja Bhojanam Thali',
    category: 'tradition',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1200&q=80',
    description: 'Celebrated Andhra royal thali served on traditional brass tableware with fresh banana leaf.',
  },
  {
    id: 'gal-5',
    title: 'Heritage Courtyard Ambience',
    category: 'ambience',
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80',
    description: 'Evening dinner under starry skies surrounded by tranquil brass water fountains and warm lanterns.',
  },
  {
    id: 'gal-6',
    title: 'Stone Ground Spices & Pure Desi Ghee',
    category: 'tradition',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80',
    description: 'Zero artificial preservatives; hand-roasted whole spices ground daily in traditional stone mills.',
  },
  {
    id: 'gal-7',
    title: 'Royal Dessert Indulgence',
    category: 'dishes',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=80',
    description: 'Nizami Khubani Ka Meetha and Shahi Double Ka Meetha made with rich saffron rabri.',
  },
  {
    id: 'gal-8',
    title: 'Private Banquets & Celebrations',
    category: 'events',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80',
    description: 'Exclusive luxury banquet suites catering to family milestone celebrations and corporate dinners.',
  },
];

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    name: 'Dr. Srinivas Rao',
    location: 'Jubilee Hills, Hyderabad',
    rating: 5,
    comment: 'Undoubtedly the best Dum Biryani and Gongura Mutton in all of Hyderabad! The aroma of pure ghee and wood smoke takes you straight back to traditional royal kitchens. Flawless ambience and very attentive staff.',
    recommendedDish: 'Nala Bheema Royal Dum Biryani',
    date: '3 days ago',
  },
  {
    id: 'rev-2',
    name: 'Priyanka Sharma',
    location: 'Banjara Hills',
    rating: 5,
    comment: 'We celebrated my mother\'s 60th birthday here. The Raja Bhojanam Thali was extraordinary—every single dish had distinct depth and balanced spice. The WhatsApp reservation and table setup was seamless!',
    recommendedDish: 'Nala Bheema Raja Bhojanam Thali',
    date: '1 week ago',
  },
  {
    id: 'rev-3',
    name: 'Vikram Aditya',
    location: 'Hitec City, Tech Executive',
    rating: 5,
    comment: 'The Araku Bamboo Biryani and Kakinada Royyala Vepudu are legendary. You can taste the freshness of the prawns and the authentic stone-ground spices. A true crown jewel for South Indian dining.',
    recommendedDish: 'Araku Bamboo Chicken Biryani',
    date: '2 weeks ago',
  },
  {
    id: 'rev-4',
    name: 'Ananya & Karthik',
    location: 'Gachibowli',
    rating: 5,
    comment: 'The ambience is magical for couples and families alike. Do not leave without trying the Apricot Delight with ice cream. Nala Bheema maintains unmatched hygiene and top-tier hospitality.',
    recommendedDish: 'Royal Khubani Apricot Delight',
    date: 'Last month',
  },
];

export const FAQS = [
  {
    q: 'Do you offer online ordering & home delivery via WhatsApp?',
    a: 'Yes! You can choose your favorite dishes directly from our online menu, add them to your cart, and click "Order via WhatsApp". Our kitchen will instantly confirm your order, preparation time, and delivery status.',
  },
  {
    q: 'Are all meats 100% Halal certified?',
    a: 'Yes, all our chicken, mutton, and poultry are 100% Halal certified, farm-fresh, and sourced daily from verified local partners under strict hygiene standards.',
  },
  {
    q: 'Is valet parking available at the restaurant?',
    a: 'Yes, we provide complimentary secure valet parking for all dine-in guests right at our grand entrance porch.',
  },
  {
    q: 'Do you cater for weddings, family functions, and corporate events?',
    a: 'Absolutely. We offer live clay-pot biryani counters, royal buffet spreads, and private banquet halls accommodating from 30 up to 400 guests.',
  },
];
